systems:
  romulus:
    uname: node230
    base_dir: /scratch/2019/visual/prf_lyon
    threads: 36
  laptop:
    uname: Tomas
    base_dir: /Users/knapen/Downloads/prf_lyon
    threads: 4

result_dir: derivatives/out
session: "01"
fmriprep_output_wildcard: fmriprep/sub-{subject}/ses-{session}}/func/sub-{subject}*_space-T1w_desc-preproc_bold.nii.gz
average_wildcard: pp/sub-{subject}/ses-{session}/func/sub-{subject}*_space-T1w_desc-preproc_bold_sg_psc.nii.gz
median_psc_filename: pp/sub-{subject}/ses-{session}/func/sub-{subject}_task-prf_acq-median_T1w_desc-preproc_bold.nii.gz
brainmask_filename: pp/sub-{subject}/ses-{session}/func/sub-{subject}_task-prf_acq-median_T1w_desc-preproc_brainmask.nii.gz
example_epi_filename: pp/sub-{subject}/ses-{session}/func/sub-{subject}_task-prf_acq-median_T1w_desc-preproc_boldref.nii.gz
cortical_mask_filename: pp/sub-{subject}/ses-{session}/func/sub-{subject}_task-prf_acq-median_T1w_desc-preproc_cortex.nii.gz
dm_file: dm.npy

TR: 1.3
cov_threshold: 0.3
fit_model: gauss_sg
grid_steps: 30
max_eccen: 12
max_n: 1.1
max_size: 9
min_eccen: 0.25
min_n: 0.05
min_size: 0.5
n_timepoints_per_run: 190
rsq_threshold: 0.1
screen_distance: 78
screen_width: 47
sg_filt_deriv: 0
sg_filt_polyorder: 3
sg_filt_window_length: 201
psc_method: median